// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR4-TdbBcydj6oGxfTfeCKcOQhiLPldk',
    appId: '1:1072948917927:web:0a94579e4d654656c30d82',
    messagingSenderId: '1072948917927',
    projectId: 'app-lista-tarefas-engsof-af7ea',
    authDomain: 'app-lista-tarefas-engsof-af7ea.firebaseapp.com',
    storageBucket: 'app-lista-tarefas-engsof-af7ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6pFEsuyNQJiRRlqCp1BFheZtA7IClJ_c',
    appId: '1:1072948917927:android:b3960a14000965b1c30d82',
    messagingSenderId: '1072948917927',
    projectId: 'app-lista-tarefas-engsof-af7ea',
    storageBucket: 'app-lista-tarefas-engsof-af7ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBes4-k-Ilj11NxTLl1dc_NFtI4oKK5y_Q',
    appId: '1:1072948917927:ios:85cad57fbebe3053c30d82',
    messagingSenderId: '1072948917927',
    projectId: 'app-lista-tarefas-engsof-af7ea',
    storageBucket: 'app-lista-tarefas-engsof-af7ea.appspot.com',
    iosBundleId: 'com.example.app08',
  );
}
